### ISSUE TITLE
`npm run local` got error

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#142]
### Error:
```
$ npm run local

> docassemble-MAEvictionDefense@0.1.0 local /.../docassemble-MAEvictionDefense
> npm run setup && npm run cucumber; npm run takedown


> docassemble-MAEvictionDefense@0.1.0 setup /.../docassemble-MAEvictionDefense
> da-setup

(node:58255) ExperimentalWarning: The fs.promises API is experimental

interview url: https://interviews-dev.gbls.org/interview?new_session=1&i=docassemble.playground42testingdccontinuevarfirst%3Atest.yml
This is meant to make sure the interview will load. Sometimes it doesn't work. If this test errors because the interview wouldn't load, you can try re-running this test.
found question on page

> docassemble-MAEvictionDefense@0.1.0 cucumber /.../docassemble-MAEvictionDefense
> run_cucumber(){ npm run cucumber_base -- "$@" tests/features/*.feature; }; run_cucumber


> docassemble-MAEvictionDefense@0.1.0 cucumber_base /.../docassemble-MAEvictionDefense
> cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "tests/features/court_dates.feature" "tests/features/example_test.feature"

(node:58271) ExperimentalWarning: The fs.promises API is experimental
..AAFF..AAAFF..AAAFF..AAAFF..AAAFF..AAAFF..AFFVError: an AfterAll hook errored, process exiting: node_modules/docassemble-cucumber/lib/steps.js:746: scope.getPrintableReport is not a function
    at _bluebird.default.each (/.../docassemble-MAEvictionDefense/node_modules/cucumber/lib/runtime/index.js:60:15)
caused by: TypeError: scope.getPrintableReport is not a function
    at /.../docassemble-MAEvictionDefense/node_modules/docassemble-cucumber/lib/steps.js:747:28
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docassemble-MAEvictionDefense@0.1.0 cucumber_base: `cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "tests/features/court_dates.feature" "tests/features/example_test.feature"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the docassemble-MAEvictionDefense@0.1.0 cucumber_base script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.../.npm/_logs/2021-01-22T16_09_43_468Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docassemble-MAEvictionDefense@0.1.0 cucumber: `run_cucumber(){ npm run cucumber_base -- "$@" tests/features/*.feature; }; run_cucumber`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the docassemble-MAEvictionDefense@0.1.0 cucumber script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.../.npm/_logs/2021-01-22T16_09_43_509Z-debug.log

> docassemble-MAEvictionDefense@0.1.0 takedown /.../docassemble-MAEvictionDefense
> da-takedown

(node:58273) ExperimentalWarning: The fs.promises API is experimental
^C
```
At the end, I waited for a while before closing out the process myself. I assume there was some kind of timeout it was waiting for. [Just occurred to me it may have been running takedown lol]

468Z log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/user_name/.nvm/versions/node/v10.13.0/bin/node',
1 verbose cli   '/Users/user_name/.nvm/versions/node/v10.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'cucumber_base',
1 verbose cli   '--',
1 verbose cli   'tests/features/court_dates.feature',
1 verbose cli   'tests/features/example_test.feature' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'precucumber_base', 'cucumber_base', 'postcucumber_base' ]
5 info lifecycle docassemble-MAEvictionDefense@0.1.0~precucumber_base: docassemble-MAEvictionDefense@0.1.0
6 info lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: docassemble-MAEvictionDefense@0.1.0
7 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: unsafe-perm in lifecycle true
8 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: PATH: /Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense/node_modules/.bin:/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense/node_modules/.bin:/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense/node_modules/.bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/Genymotion.app/Contents/MacOS/tools:/Users/user_name/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/opt/X11/bin
9 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: CWD: /Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense
10 silly lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: Args: [ '-c',
10 silly lifecycle   'cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "tests/features/court_dates.feature" "tests/features/example_test.feature"' ]
11 silly lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: Returned: code: 1  signal: null
12 info lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber_base: Failed to exec cucumber_base script
13 verbose stack Error: docassemble-MAEvictionDefense@0.1.0 cucumber_base: `cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "tests/features/court_dates.feature" "tests/features/example_test.feature"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid docassemble-MAEvictionDefense@0.1.0
15 verbose cwd /Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense
16 verbose Darwin 18.6.0
17 verbose argv "/Users/user_name/.nvm/versions/node/v10.13.0/bin/node" "/Users/user_name/.nvm/versions/node/v10.13.0/bin/npm" "run" "cucumber_base" "--" "tests/features/court_dates.feature" "tests/features/example_test.feature"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error docassemble-MAEvictionDefense@0.1.0 cucumber_base: `cucumber-js --require ./node_modules/docassemble-cucumber/lib/index.js "tests/features/court_dates.feature" "tests/features/example_test.feature"`
22 error Exit status 1
23 error Failed at the docassemble-MAEvictionDefense@0.1.0 cucumber_base script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

509Z log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/user_name/.nvm/versions/node/v10.13.0/bin/node',
1 verbose cli   '/Users/user_name/.nvm/versions/node/v10.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'cucumber' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'precucumber', 'cucumber', 'postcucumber' ]
5 info lifecycle docassemble-MAEvictionDefense@0.1.0~precucumber: docassemble-MAEvictionDefense@0.1.0
6 info lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: docassemble-MAEvictionDefense@0.1.0
7 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: unsafe-perm in lifecycle true
8 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: PATH: /Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense/node_modules/.bin:/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense/node_modules/.bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/Genymotion.app/Contents/MacOS/tools:/Users/user_name/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/MacGPG2/bin:/opt/X11/bin
9 verbose lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: CWD: /Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense
10 silly lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: Args: [ '-c',
10 silly lifecycle   'run_cucumber(){ npm run cucumber_base -- "$@" tests/features/*.feature; }; run_cucumber' ]
11 silly lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: Returned: code: 1  signal: null
12 info lifecycle docassemble-MAEvictionDefense@0.1.0~cucumber: Failed to exec cucumber script
13 verbose stack Error: docassemble-MAEvictionDefense@0.1.0 cucumber: `run_cucumber(){ npm run cucumber_base -- "$@" tests/features/*.feature; }; run_cucumber`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/user_name/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid docassemble-MAEvictionDefense@0.1.0
15 verbose cwd /Users/user_name/Desktop/General/coding/suffolk-lit-lab/docassemble-MAEvictionDefense
16 verbose Darwin 18.6.0
17 verbose argv "/Users/user_name/.nvm/versions/node/v10.13.0/bin/node" "/Users/user_name/.nvm/versions/node/v10.13.0/bin/npm" "run" "cucumber"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error docassemble-MAEvictionDefense@0.1.0 cucumber: `run_cucumber(){ npm run cucumber_base -- "$@" tests/features/*.feature; }; run_cucumber`
22 error Exit status 1
23 error Failed at the docassemble-MAEvictionDefense@0.1.0 cucumber script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by plocket** [comment]
Nevermind, I'm getting it with `test` as well. `*`Sigh`*`
