### ISSUE TITLE
Hunt down `Error: net::ERR_ABORTED`

### ISSUE THREAD

**Issue by plocket** [plocket/docassemble-cucumber#585]
Around comit 0e116bd3e687505e0aafcbe65d3de06fe53aa95e, I started seeing an error pop up inconsistently. The possibility must have been present before that, though, because changing the code back didn't solve the problem.

```
1) Scenario: Fail with missng language link (attempt 1, retried) # tests/features/reports.feature:15
   ✔ Before # lib/steps.js:104
   ✔ Given the final Scenario status should be "failed" # lib/steps.js:1052
   ✔ Given the Scenario report should include: # lib/steps.js:1039
       """
       Could not find the link with the text "Latin"
       """
   ✔ And I start the interview at "all_tests" in lang "Latin" # lib/steps.js:156
   ✖ After # lib/steps.js:1066
       Error: net::ERR_ABORTED at https://apps-dev.suffolklitlab.org/user/sign-out
           at navigate (/Users/Comfadorable/Desktop/General/coding/suffolk-lit-lab-assembly-line/docassemble-cucumber/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:155:23)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at async FrameManager.navigateFrame (/Users/Comfadorable/Desktop/General/coding/suffolk-lit-lab-assembly-line/docassemble-cucumber/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:130:21)
           at async Frame.goto (/Users/Comfadorable/Desktop/General/coding/suffolk-lit-lab-assembly-line/docassemble-cucumber/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:501:16)
           at async Page.goto (/Users/Comfadorable/Desktop/General/coding/suffolk-lit-lab-assembly-line/docassemble-cucumber/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)
           at async World.<anonymous> (/Users/Comfadorable/Desktop/General/coding/suffolk-lit-lab-assembly-line/docassemble-cucumber/lib/steps.js:1147:7)
```

It sometimes showed up on the first attempt, sometimes on both attempts, and sometimes not at all. It consistently appeared for only the Scenario shown in the error message: `Fail with missng language link`.

The commit is currently in the PR #392. I'm not exactly sure it's a bug yet.

**Comment by plocket** [comment]
Not sure why I didn't notice this before, but the error is on the `sign-out` page. This was probably just a set of unfortunate server reload problem coincidences.
