### ISSUE TITLE
Random input test fails with Puppeteer error

### ISSUE THREAD

**Issue by BryceStevenWilley** [plocket/docassemble-cucumber#627]
I can come back to this when I have the time, just had a few minutes this morning and tried running a few random tests to see if I found anything.

Run on [AppearanceEfile](https://github.com/SuffolkLITLab/docassemble-AppearanceEfile), the following tests:

```feature
Scenario: random inputs
  Given I start the interview at "appearance.yml"
  Then I answer randomly for at most 100 pages
```

2 of three times ended with this error:

```
1) Scenario: random inputs (attempt 2) # docassemble/AppearanceEfile/data/sources/interviews_run.feature:170
   ✔ Before # ../ALKiln/lib/steps.js:103
   ✔ Given I start the interview at "appearance.yml" # ../ALKiln/lib/steps.js:156
   ✖ Then I answer randomly for at most 100 pages # ../ALKiln/lib/steps.js:776
       Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'nextSibling')
           at __puppeteer_evaluation_script__:6:17
           at ExecutionContext._evaluateInternal (/home/brycew/Developer/LITLab/code/ALKiln/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at async Object.get_handle_from_field (/home/brycew/Developer/LITLab/code/ALKiln/lib/scope.js:1581:18)
           at async Object.buttons (/home/brycew/Developer/LITLab/code/ALKiln/lib/scope.js:2653:20)
           at async /home/brycew/Developer/LITLab/code/ALKiln/lib/steps.js:860:13
```

On screen that only had a continue button (the instructions screen).

**Comment by plocket** [comment]
Just as a point of information: Can you tell if there are other pages that only have a continue button that _didn't_ fail?

[In case you haven't had this thought yet: it looks like something's incorrectly looking for a sibling element of the button for some reason. iirc, that's done for checkboxes and radio buttons. I don't remember details beyond that atm.]

**Comment by BryceStevenWilley** [comment]
I mean, it definitely is some sort of race condition? IT doesn't consistently fail on those pages (TBH, don't have enough info to know what pages it gets to, but there's a fairly hard block in the test I was doing).

Started partial work on this in https://github.com/SuffolkLITLab/ALKiln/tree/random_fixes, there were still a few more issues I was running into though.
